
export interface Language {
  id: string;
  code: string;
  name: string;
  nativeName?: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { id: "b18144fa", code: "ab", name: "Abkhaz", nativeName: "Abkhaz" },
  { id: "b250199b", code: "ace", name: "Acehnese", nativeName: "Acehnese" },
  { id: "77682ffe", code: "ach", name: "Acholi", nativeName: "Acholi" },
  { id: "5e5382dc", code: "af", name: "Afrikaans", nativeName: "Afrikaans" },
  { id: "c540dc14", code: "sq", name: "Albanian", nativeName: "Shqip" },
  { id: "9210031e", code: "alz", name: "Alur", nativeName: "Alur" },
  { id: "8e3b070c", code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { id: "212b7d5d", code: "ar", name: "Arabic", nativeName: "العربية" },
  { id: "ff74ba2b", code: "hy", name: "Armenian", nativeName: "Հայերեն" },
  { id: "d843c776", code: "as", name: "Assamese", nativeName: "অসমীয়া" },
  { id: "324b68aa", code: "awa", name: "Awadhi", nativeName: "Awadhi" },
  { id: "ace94a47", code: "ay", name: "Aymara", nativeName: "Aymara" },
  { id: "5845b970", code: "az", name: "Azerbaijani", nativeName: "Azərbaycan" },
  { id: "0bd31ccb", code: "ban", name: "Balinese", nativeName: "Balinese" },
  { id: "5d452b43", code: "bm", name: "Bambara", nativeName: "Bambara" },
  { id: "e03a4670", code: "ba", name: "Bashkir", nativeName: "Bashkir" },
  { id: "21d6d816", code: "eu", name: "Basque", nativeName: "Euskara" },
  { id: "aefcf3ed", code: "btx", name: "Batak Karo", nativeName: "Batak Karo" },
  { id: "652ffb94", code: "bts", name: "Batak Simalungun", nativeName: "Batak Simalungun" },
  { id: "16ff3f87", code: "bbc", name: "Batak Toba", nativeName: "Batak Toba" },
  { id: "0e3f9e7b", code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { id: "05dd1419", code: "bem", name: "Bemba", nativeName: "Bemba" },
  { id: "5e9f359f", code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { id: "afef1ce0", code: "bew", name: "Betawi", nativeName: "Betawi" },
  { id: "1b3db624", code: "bho", name: "Bhojpuri", nativeName: "Bhojpuri" },
  { id: "82f9ef92", code: "bik", name: "Bikol", nativeName: "Bikol" },
  { id: "539772c5", code: "brx", name: "Bodo", nativeName: "" },
  { id: "74c6674e", code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { id: "a3dd0cc4", code: "br", name: "Breton", nativeName: "Breton" },
  { id: "aec41c94", code: "bg", name: "Bulgarian", nativeName: "Български" },
  { id: "6ded0ad4", code: "bua", name: "Buryat", nativeName: "Buryat" },
  { id: "ff26f125", code: "yue", name: "Cantonese", nativeName: "粵語" },
  { id: "e538c3c6", code: "ca", name: "Catalan", nativeName: "Català" },
  { id: "00001e56", code: "ceb", name: "Cebuano", nativeName: "Cebuano" },
  { id: "f2200794", code: "hne", name: "Chhattisgarhi", nativeName: "" },
  { id: "eb44379a", code: "ny", name: "Chichewa (Nyanja)", nativeName: "Chichewa" },
  { id: "4bb2b412", code: "zh", name: "Chinese", nativeName: "" },
  { id: "64cda98b", code: "lzh", name: "Chinese (Literary)", nativeName: "" },
  { id: "b0b120b6", code: "zh-CN", name: "Chinese (Simplified)", nativeName: "简体中文" },
  { id: "500957cf", code: "zh-TW", name: "Chinese (Traditional)", nativeName: "繁體中文" },
  { id: "3fa80c95", code: "co", name: "Corsican", nativeName: "Corsican" },
  { id: "563ff786", code: "crh", name: "Crimean Tatar", nativeName: "Crimean Tatar" },
  { id: "748ca1c3", code: "hr", name: "Croatian", nativeName: "Hrvatski" },
  { id: "38657080", code: "cs", name: "Czech", nativeName: "Čeština" },
  { id: "a4b96446", code: "da", name: "Danish", nativeName: "Dansk" },
  { id: "8f2d708d", code: "prs", name: "Dari", nativeName: "" },
  { id: "2fee9e62", code: "din", name: "Dinka", nativeName: "Dinka" },
  { id: "f5c6e3db", code: "dv", name: "Divehi", nativeName: "Divehi" },
  { id: "31d10d53", code: "doi", name: "Dogri", nativeName: "Dogri" },
  { id: "2d5465b8", code: "dov", name: "Dombe", nativeName: "Dombe" },
  { id: "30e318e2", code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { id: "56fd676a", code: "dz", name: "Dzongkha", nativeName: "Dzongkha" },
  { id: "d72ec609", code: "en", name: "English", nativeName: "English" },
  { id: "fe291fe3", code: "en-AU", name: "English (AU)", nativeName: "" },
  { id: "2d1ec56d", code: "en-GB", name: "English (UK)", nativeName: "" },
  { id: "dbe695d8", code: "en-US", name: "English (US)", nativeName: "" },
  { id: "f581c611", code: "eo", name: "Esperanto", nativeName: "Esperanto" },
  { id: "2c4002e1", code: "et", name: "Estonian", nativeName: "Eesti" },
  { id: "6945baf2", code: "ee", name: "Ewe", nativeName: "Ewe" },
  { id: "c3df6b00", code: "fo", name: "Faroese", nativeName: "" },
  { id: "4f783051", code: "fj", name: "Fijian", nativeName: "Fijian" },
  { id: "b177e1d8", code: "fil", name: "Filipino (Tagalog)", nativeName: "Filipino" },
  { id: "07472e84", code: "fi", name: "Finnish", nativeName: "Suomi" },
  { id: "f9d84573", code: "fon", name: "Fon", nativeName: "Fɔ̀ngbè" },
  { id: "4d51a2e9", code: "fr", name: "French", nativeName: "Français" },
  { id: "04e63044", code: "fr-CA", name: "French (Canadian)", nativeName: "Français (Canada)" },
  { id: "25530c80", code: "fy", name: "Frisian", nativeName: "Frisian" },
  { id: "5abae786", code: "ff", name: "Fulfulde", nativeName: "Fulfulde" },
  { id: "588eceec", code: "gaa", name: "Ga", nativeName: "Ga" },
  { id: "2af7ea39", code: "gl", name: "Galician", nativeName: "Galician" },
  { id: "d8b083f4", code: "lg", name: "Ganda (Luganda)", nativeName: "Luganda" },
  { id: "4ee4cbbe", code: "ka", name: "Georgian", nativeName: "ქართული" },
  { id: "2d9c8dda", code: "de", name: "German", nativeName: "Deutsch" },
  { id: "68c36076", code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { id: "900b589d", code: "gn", name: "Guarani", nativeName: "Guarani" },
  { id: "5b9bf19a", code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { id: "511ba6ee", code: "ht", name: "Haitian Creole", nativeName: "Haitian Creole" },
  { id: "55a95e5a", code: "cnh", name: "Hakha Chin", nativeName: "Hakha Chin" },
  { id: "f35d9172", code: "ha", name: "Hausa", nativeName: "هَرْشٜىٰن هَوْسَا" },
  { id: "5330d2aa", code: "haw", name: "Hawaiian", nativeName: "Hawaiian" },
  { id: "7c055b27", code: "he", name: "Hebrew", nativeName: "עברית" },
  { id: "418d3eb2", code: "hil", name: "Hiligaynon", nativeName: "Hiligaynon" },
  { id: "6b321b95", code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { id: "b4388def", code: "hmn", name: "Hmong", nativeName: "Hmong" },
  { id: "6fafd652", code: "mww", name: "Hmong Daw (Latin)", nativeName: "" },
  { id: "1ee230c1", code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { id: "21f6fa5d", code: "hrx", name: "Hunsrik", nativeName: "Hunsrik" },
  { id: "3209d8b7", code: "is", name: "Icelandic", nativeName: "Íslenska" },
  { id: "c516891b", code: "ig", name: "Igbo", nativeName: "Igbo" },
  { id: "3acd0f90", code: "ilo", name: "Iloko", nativeName: "Iloko" },
  { id: "826a8a5b", code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { id: "b556352b", code: "ikt", name: "Inuinnaqtun", nativeName: "" },
  { id: "8285b9cc", code: "iu", name: "Inuktitut", nativeName: "" },
  { id: "8f1494e6", code: "iu-Latn", name: "Inuktitut (Latin)", nativeName: "" },
  { id: "a659095a", code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { id: "ad38f8c5", code: "it", name: "Italian", nativeName: "Italiano" },
  { id: "14ad584e", code: "ja", name: "Japanese", nativeName: "日本語" },
  { id: "6df50a98", code: "jv", name: "Javanese", nativeName: "Javanese" },
  { id: "23cc8594", code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { id: "04a12562", code: "pam", name: "Kapampangan", nativeName: "Kapampangan" },
  { id: "528f5594", code: "ks", name: "Kashmiri", nativeName: "" },
  { id: "aa303f8f", code: "kk", name: "Kazakh", nativeName: "Қазақ" },
  { id: "d36c54b5", code: "km", name: "Khmer", nativeName: "ខ្មែរ" },
  { id: "c7aa5b2e", code: "cgg", name: "Kiga", nativeName: "Kiga" },
  { id: "76fc732b", code: "rw", name: "Kinyarwanda", nativeName: "Kinyarwanda" },
  { id: "4f5bce8b", code: "ktu", name: "Kituba", nativeName: "Kituba" },
  { id: "e41eea68", code: "gom", name: "Konkani", nativeName: "Konkani" },
  { id: "5be876f5", code: "ko", name: "Korean", nativeName: "한국어" },
  { id: "ce2da331", code: "kri", name: "Krio", nativeName: "Krio" },
  { id: "5dbcbf0c", code: "ku", name: "Kurdish (Kurmanji)", nativeName: "Kurdî" },
  { id: "fc6e7fbf", code: "kmr", name: "Kurdish (Northern)", nativeName: "" },
  { id: "286314ff", code: "ckb", name: "Kurdish (Sorani)", nativeName: "کوردی" },
  { id: "d3f97113", code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { id: "f6a7a57c", code: "lo", name: "Lao", nativeName: "ລາວ" },
  { id: "9592642e", code: "ltg", name: "Latgalian", nativeName: "Latgalian" },
  { id: "66a1e786", code: "la", name: "Latin", nativeName: "Latin" },
  { id: "da63ef17", code: "lv", name: "Latvian", nativeName: "Latviešu" },
  { id: "83a3d696", code: "lij", name: "Ligurian", nativeName: "Ligurian" },
  { id: "279d3df9", code: "li", name: "Limburgan", nativeName: "Limburgan" },
  { id: "4d620733", code: "ln", name: "Lingala", nativeName: "Lingala" },
  { id: "93524750", code: "lt", name: "Lithuanian", nativeName: "Lietuvių" },
  { id: "685b13f9", code: "lmo", name: "Lombard", nativeName: "Lombard" },
  { id: "3ebb469d", code: "dsb", name: "Lower Sorbian", nativeName: "" },
  { id: "c1efe1c5", code: "lug", name: "Luganda", nativeName: "" },
  { id: "8f51c941", code: "luo", name: "Luo", nativeName: "Luo" },
  { id: "cd637d09", code: "lb", name: "Luxembourgish", nativeName: "Luxembourgish" },
  { id: "37d37c9e", code: "mk", name: "Macedonian", nativeName: "Македонски" },
  { id: "d0682035", code: "mai", name: "Maithili", nativeName: "Maithili" },
  { id: "64c6e319", code: "mak", name: "Makassar", nativeName: "Makassar" },
  { id: "1ab3b376", code: "mg", name: "Malagasy", nativeName: "Malagasy" },
  { id: "8ba8f651", code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { id: "48b93abc", code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { id: "0e6b1a06", code: "mt", name: "Maltese", nativeName: "Malti" },
  { id: "454e10b4", code: "mni", name: "Manipuri", nativeName: "" },
  { id: "ef5c5deb", code: "mi", name: "Maori", nativeName: "Māori" },
  { id: "d3e0b200", code: "mr", name: "Marathi", nativeName: "मराठी" },
  { id: "a5480a45", code: "chm", name: "Meadow Mari", nativeName: "Meadow Mari" },
  { id: "efa759e8", code: "mni-Mtei", name: "Meiteilon (Manipuri)", nativeName: "Meiteilon" },
  { id: "ec3f091f", code: "min", name: "Minang", nativeName: "Minang" },
  { id: "b4d5edfa", code: "lus", name: "Mizo", nativeName: "Mizo" },
  { id: "abe29b89", code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { id: "50455e55", code: "mn-Mong", name: "Mongolian (Traditional)", nativeName: "" },
  { id: "bc5cb387", code: "my", name: "Myanmar (Burmese)", nativeName: "မြန်မာ" },
  { id: "9a04dad9", code: "nr", name: "Ndebele (South)", nativeName: "Ndebele" },
  { id: "d5f7a4e4", code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { id: "7b2e0143", code: "new", name: "Nepalbhasa (Newari)", nativeName: "Nepalbhasa" },
  { id: "a5c50907", code: "nso", name: "Northern Sotho (Sepedi)", nativeName: "Sepedi" },
  { id: "f95c7063", code: "no", name: "Norwegian", nativeName: "Norsk" },
  { id: "30278c80", code: "nus", name: "Nuer", nativeName: "Nuer" },
  { id: "8ce1aed8", code: "nya", name: "Nyanja", nativeName: "" },
  { id: "fc9a2d07", code: "oc", name: "Occitan", nativeName: "Occitan" },
  { id: "ed7256f3", code: "or", name: "Odia (Oriya)", nativeName: "ଓଡ଼ିଆ" },
  { id: "e89a09e7", code: "om", name: "Oromo", nativeName: "Oromo" },
  { id: "7cf1a6ad", code: "pag", name: "Pangasinan", nativeName: "Pangasinan" },
  { id: "fc09d969", code: "pap", name: "Papiamento", nativeName: "Papiamento" },
  { id: "aa901adf", code: "ps", name: "Pashto", nativeName: "پښتو" },
  { id: "7f2be16a", code: "fa", name: "Persian", nativeName: "فارسی" },
  { id: "c6787407", code: "pl", name: "Polish", nativeName: "Polski" },
  { id: "3e9b85bd", code: "pt", name: "Portuguese", nativeName: "Português" },
  { id: "aa17b231", code: "pt-BR", name: "Portuguese (Brazil)", nativeName: "Português (Brasil)" },
  { id: "9e13a09f", code: "pt-PT", name: "Portuguese (Portugal)", nativeName: "Português (Portugal)" },
  { id: "80c6371c", code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { id: "8e5775ce", code: "pa-Arab", name: "Punjabi (Arabic script)", nativeName: "" },
  { id: "bed2bc2f", code: "qu", name: "Quechua", nativeName: "Quechua" },
  { id: "b9d83779", code: "otq", name: "Queretaro Otomi", nativeName: "" },
  { id: "59a223cb", code: "rom", name: "Romani", nativeName: "Romani" },
  { id: "b728c9b7", code: "ro", name: "Romanian", nativeName: "Română" },
  { id: "22c79bdd", code: "rn", name: "Rundi", nativeName: "Rundi" },
  { id: "0156b0f5", code: "ru", name: "Russian", nativeName: "Русский" },
  { id: "e2ca86bd", code: "sm", name: "Samoan", nativeName: "Samoan" },
  { id: "d5a9b057", code: "sg", name: "Sango", nativeName: "Sango" },
  { id: "90d6f9bc", code: "sa", name: "Sanskrit", nativeName: "Sanskrit" },
  { id: "8bc8e37e", code: "gd", name: "Scots Gaelic", nativeName: "Scots Gaelic" },
  { id: "52b333a5", code: "sr", name: "Serbian", nativeName: "Српски" },
  { id: "10e60174", code: "st", name: "Sesotho", nativeName: "Sesotho" },
  { id: "2bc535e1", code: "crs", name: "Seychellois Creole", nativeName: "Seychellois Creole" },
  { id: "936a15fe", code: "shn", name: "Shan", nativeName: "Shan" },
  { id: "87a7d022", code: "sn", name: "Shona", nativeName: "Shona" },
  { id: "f7ac1457", code: "scn", name: "Sicilian", nativeName: "Sicilian" },
  { id: "93d6f1ed", code: "szl", name: "Silesian", nativeName: "Silesian" },
  { id: "0de2d60b", code: "sd", name: "Sindhi", nativeName: "Sindhi" },
  { id: "0fa293ad", code: "si", name: "Sinhala", nativeName: "සිංහල" },
  { id: "d832bdb6", code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { id: "db3d8cc7", code: "sl", name: "Slovenian", nativeName: "Slovenščina" },
  { id: "e5788af5", code: "so", name: "Somali", nativeName: "Somali" },
  { id: "6e8b782d", code: "es", name: "Spanish", nativeName: "Español" },
  { id: "c944083b", code: "es-MX", name: "Spanish (Mexico)", nativeName: "" },
  { id: "f22c51e9", code: "es-ES", name: "Spanish (Spain)", nativeName: "" },
  { id: "fc9e3ee6", code: "su", name: "Sundanese", nativeName: "Sundanese" },
  { id: "a2ed45d0", code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { id: "ef05968d", code: "ss", name: "Swati", nativeName: "Swati" },
  { id: "a7c47120", code: "sv", name: "Swedish", nativeName: "Svenska" },
  { id: "e04ca782", code: "ty", name: "Tahitian", nativeName: "" },
  { id: "a58ef775", code: "tg", name: "Tajik", nativeName: "Тоҷикӣ" },
  { id: "96de04f9", code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { id: "68133966", code: "tt", name: "Tatar", nativeName: "Tatar" },
  { id: "21d63c5e", code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { id: "5644c034", code: "tet", name: "Tetum", nativeName: "Tetum" },
  { id: "1ee59f79", code: "th", name: "Thai", nativeName: "ไทย" },
  { id: "9da24cc5", code: "bo", name: "Tibetan", nativeName: "" },
  { id: "5f4bc6ab", code: "ti", name: "Tigrinya", nativeName: "Tigrinya" },
  { id: "2881f06d", code: "to", name: "Tongan", nativeName: "" },
  { id: "9d6a53fd", code: "ts", name: "Tsonga", nativeName: "Tsonga" },
  { id: "4b33c5ca", code: "tn", name: "Tswana", nativeName: "Tswana" },
  { id: "11683cb7", code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { id: "e7d8a680", code: "tk", name: "Turkmen", nativeName: "Turkmen" },
  { id: "882a6e2a", code: "ak", name: "Twi (Akan)", nativeName: "Twi" },
  { id: "811fb367", code: "ug", name: "Uyghur", nativeName: "Uyghur" },
  { id: "b8705318", code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { id: "f771978c", code: "hsb", name: "Upper Sorbian", nativeName: "" },
  { id: "0f799819", code: "ur", name: "Urdu", nativeName: "اردو" },
  { id: "0b8c4da7", code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { id: "090424cb", code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { id: "54ebcae7", code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { id: "93ad22be", code: "xh", name: "Xhosa", nativeName: "Xhosa" },
  { id: "ce465aba", code: "yi", name: "Yiddish", nativeName: "Yiddish" },
  { id: "fa297223", code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { id: "f1e9b95b", code: "yua", name: "Yucatec Maya", nativeName: "Yucatec Maya" },
  { id: "44023693", code: "zu", name: "Zulu", nativeName: "Zulu" },
].sort((a, b) => a.name.localeCompare(b.name));

// Subset of languages optimized for high-quality real-time audio interaction (Live API)
export const LIVE_SUPPORTED_LANGUAGES: Language[] = SUPPORTED_LANGUAGES.filter(lang => 
  [
    'Arabic', 
    'Chinese (Simplified)', 
    'Chinese (Traditional)', 
    'Czech', 
    'Danish', 
    'Dutch', 
    'English', 
    'English (UK)', 
    'English (US)', 
    'Finnish', 
    'French', 
    'German', 
    'Greek', 
    'Hebrew', 
    'Hindi', 
    'Indonesian', 
    'Italian', 
    'Japanese', 
    'Korean', 
    'Norwegian', 
    'Polish', 
    'Portuguese', 
    'Portuguese (Brazil)', 
    'Romanian', 
    'Russian', 
    'Spanish', 
    'Swedish', 
    'Thai', 
    'Turkish', 
    'Ukrainian', 
    'Vietnamese'
  ].includes(lang.name)
);
